### ISSUE TITLE
Documentation for swarm + contiv installation

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#10]
there is no documentation for swarm installation+ contiv here .
It used to be there earlier in netplugin/install.
1: should we copy that ?
2: Should we just maintain one repo : contiv/netplugin for all installers ?

**Comment by neelimamukiri** [comment]
@gaurav-dalvi, does the information in https://github.com/contiv/install cover what you had in mind or is there additional information needed?

**Comment by rhim** [comment]
ping @gaurav-dalvi

**Comment by gaurav-dalvi** [comment]
It would be better to add example on : Using your customized aci-gw container version to be fetched from docker hub.

**Comment by neelimamukiri** [comment]
We do not expect end users to specify aci-gw version. Also if you specify a custom version, it wont work with the default full installer. As the option is documented in the installer https://github.com/contiv/install/blob/master/install/ansible/install_swarm.sh#L39-L40 and is not expected to be used by regular users (as we will push the latest aci-gw image to docker hub), I think we are good with the documentation. Closing this issue. Please re-open or file a new issue if there is any further documentation required.
