### ISSUE TITLE
In Full contiv build , include reduced size contiv/aci-gw:latest image

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#119]
@neelimamukiri : We need to put contiv/aci-gw:latest image inside full build.

**Comment by neelimamukiri** [comment]
Why is this required? We used to see that for most normal network speed setups, docker load was taking much longer than docker pull/run.

**Comment by neelimamukiri** [comment]
Per offline discussion, there was an update to aci-gw:latest image after the 1.0 release was made. This can be picked up either using the minimal install build or will be packaged in the next build of the installer (automatically as part of the build process. See https://github.com/contiv/install/blob/master/scripts/build.sh#L129).

We should not update the release bits manually to include the new image. If required users can always replace the aci-gw bits as mentioned above.
