### ISSUE TITLE
uninstaller does not clean up docker containers

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#12]
docker swarm + contiv one does not clean up containers.

Unsintall should do EXACT reverse of all the tasks we are doing with installer so that we can get our VMs back in original shape.

**Comment by neelimamukiri** [comment]
We need a reset option to clear the state from the installation for demo purposes and other clean/purge use cases.
For docker/swarm this is to remove containers.
For etcd this is not an issue as there is no persistent store backing (https://github.com/contiv/ansible/issues/317 is tracking this so we can allow for uninstall/install/upgrade scenarios without purging data). When https://github.com/contiv/ansible/issues/317 is fixed the cleanup should also support the reset option.
