### ISSUE TITLE
Process for Installing Contiv with K8s

### ISSUE THREAD

**Issue by spirrello** [contiv/install#121]
I feel there should be a process for installing Contiv with a working installation of K8s.  If you look at other products such as Calico or Flannel, they have these well documented.  This instruction on this page fall short where they're dependant of Kubeadm - you can't use Kubeadm in production as it doesn't support a multi-master deployment.

My recommendation is to document the process for installing Contiv with a working installation of K8s.

**Comment by gaurav-dalvi** [comment]
Ping @neelimamukiri @dojacobs

**Comment by dojacobs** [comment]
The process Jenkins (Netplugin_End-to-End) uses is this:

Assume I have deployed nodes K8s Master (M), and 2 nodes (N1, N2) running Centos. (in Jenkins this is done via terraform.)

First, copy the centos_bootstrap.sh script to M, N1, and N2, and execute (sudo bash centos_bootstrap.sh)

Next, copy k8smaster.sh to M and execute.  Copy k8sworker.sh to N1 and N2 and execute.

Finally, copy the contiv installer tarball to M, and untar.  Now run the installer.

You should now have a K8s cluster with Contiv installed.

Issues:
* centos_bootstrap.sh, k8smaster.sh and k8sworker.sh all come from GIT:contiv/install.   They are not in the installer tarball (contiv-1.0.0-rc1.tgz)

* Still no easy way to bring up a container - have to create pod.yaml for kubectl.  Format of this file is not well documented by K8s.  It is possible to bring up a pod with kubectl alone but you're basically typing in the entire yaml file by hand.

* Issues with K8s on nodes that have multiple network interfaces.  Solution is to manually edit /etc/hosts on all 3 VMs however it would be nice if our installer handled that for the customer. (we are the networking folks, right? :-) )

**Comment by neelimamukiri** [comment]
@dojacobs, @gaurav-dalvi, the request is for an ansible based installer, that installs Contiv as host systemd services (https://github.com/contiv/ccn/issues/274). CC @unclejack

**Comment by spirrello** [comment]
I'd be fine with Ansible installer....truth be told, I think a _step by step_ process would be better to allow the community to formalize their own automated process.

@dojacobs does the process you've posted accommodate a multi master setup?  Are there an inventory files that need to be prepopulated ahead of time?

**Comment by dojacobs** [comment]
@spirrello : My process in Jenkins only handles the case of 1 master, multiple workers.

Jenkins runs the command:  terraform output , to get the list of IP#s of the VMs that were spun up.  The first IP is always assumed to be the master, whereas the others are assumed to be workers.  The master has the k8smaster.sh script run on it, whereas the workers have k8sworker.sh run on them.  Then the installer is run on the master.

It should not be difficult to modify Jenkins to handle a multi-master setup.  Just have to split the list from terraform such that you have a list of masters, and a list of workers.

**Comment by spirrello** [comment]
Doug,

Are these the scripts you're referring to?

https://github.com/contiv/install/tree/master/cluster/k8s1.6

**Comment by rhim** [comment]
@dojacobs the script you mention above uses kubeadm underneath.

@spirrello the ansible based install of contiv for k8s is WIP. Stay tuned.
