### ISSUE TITLE
Documentation for kubernetes install

### ISSUE THREAD

**Issue by riffraff169** [contiv/install#13]
Document says to continue to kubernetes install getting started page.  Per @neelimamukiri , should skip step 3, labeled (3/4) Installing a pod network.  The contiv install is done instead of step 3.  Also, it could be mentioned that step 4 (Joining nodes) of the kubernetes install can be done either before or after step 3 (which would be running the contiv install).

**Comment by neelimamukiri** [comment]
Added this to the README pre-requisites section.
