### ISSUE TITLE
Fail to installfor for contiv, failure prompt information is  passwordless ssh 

### ISSUE THREAD

**Issue by yanyuxiyangzk** [contiv/install#140]
Starting the installer container
Generating Ansible configuration
Using 172.17.0.2 as the master node
Verifying ansible reachability
WARNING Some of the hosts are not accessible via passwordless SSH
 
This means either the host is unreachable or passwordless SSH is not
set up for it. Please resolve this before proceeding.

**Comment by yanyuxiyangzk** [comment]
contiv version  is  1.0.2

**Comment by rhim** [comment]
@yanyuxiyangzk can you please ensure that you can ssh onto the nodes specified in yaml without providing password?

**Comment by yanyuxiyangzk** [comment]
Well, i have three machines, which ip is 192.168.2.10,192.168.2.11,192168.2.12. The first noe 192.168.2.10 is docker container,and ssh to 192.168.2.11,192.16.8.2.12 for with out password to visit,eg ssh root@192.168.2.11 ,then login in it with out input password.
Then i perform this command ./install/ansible/install_swarm.sh -f install/ansible/cfg.yml -e ~/.ssh/authorized_keys -u root -i ,but a fault has occurred . the message is ssh .......

在 2017-05-31 04:48:32，"Himanshu Raj" <notifications@github.com> 写道：


@yanyuxiyangzk can you please ensure that you can ssh onto the nodes specified in yaml without providing password?

**Comment by rhim** [comment]
-e option requires you to specify the private key – so it will be something like ~/.ssh/id_rsa.

- Himanshu
     .:|:.:|:.

**Comment by yanyuxiyangzk** [comment]
Well, i have three machines, which ip is 192.168.2.10,192.168.2.11,192168.2.12. The first noe 192.168.2.10 is docker container,and ssh to 192.168.2.11,192.16.8.2.12 for with out password to visit,eg ssh root@192.168.2.11 ,then login in it with out input password.
Then i perform this command ./install/ansible/install_swarm.sh -f install/ansible/cfg.yml -e ~/.ssh/authorized_keys -u root -i ,but a fault has occurred . the message is ssh .......

在 2017-05-31 04:48:32，"Himanshu Raj" <notifications@github.com> 写道：


@yanyuxiyangzk can you please ensure that you can ssh onto the nodes specified in yaml without providing password?

**Comment by gaurav-dalvi** [comment]
@rhim : can close this one ?

**Comment by rhim** [comment]
Is this confirmed working?
- Himanshu
     .:|:.:|:.

On Jun 6, 2017, at 3:13 PM, Gaurav Dalvi <notifications@github.com<mailto:notifications@github.com>> wrote:


@rhim<https://github.com/rhim> : can close this one ?
