### ISSUE TITLE
v2Plugin Install env.json errors

### ISSUE THREAD

**Issue by rkharya** [contiv/install#141]
Syntax errors in env.jason -

[root@NFS contiv-full-1.0.2]# diff env.json env.json.org
7c7
<   "service_vip":"10.65.122.61",
---
>   "service_vip": "__NETMASTER_IP__",
9c9
<   "cluster_store":"etcd://10.65.122.61:2379",
---
>   "cluster_store": "__CLUSTER_STORE__",
14,16c14,16
<   "auth_proxy_local_install": "True",
<   "contiv_network_local_install": "True",
<   "contiv_v2plugin_install": "True",
---
>   "auth_proxy_local_install": True,
>   "contiv_network_local_install": True <<<<< 'comma' is missing
>   "contiv_v2plugin_install": "False", <<<< This should be True, as we want to install v2Plugin

Due to these discrepancies, v2Plugin installation is failing. For now we have edited the ymal to move forward.

Thanks,

**Comment by gkvijay** [comment]
@rkharya, Hope you downloaded the tar file (in install instructions) for the new version. The comma seems to be there in the repo:
https://github.com/contiv/install/blob/master/install/ansible/env.json#L15

contiv_v2plugin_install will be set to False by default. Currently, you need to change it to True manually. I will push a change to automatically change it when the installer is run with "-p" option.

**Comment by rkharya** [comment]
@gkvijay, Yes we downloaded the tar file, as given in the installation instructions, for 1.0.2 only. I verified the missing 'comma' twice by extracting the tar ball twice. Surprisingly, its missing in the archive but code as you have shown, does have it. We may need to look it more closely as to where its breaking.
