### ISSUE TITLE
v2Plugin install fails on Existing Swarm cluster

### ISSUE THREAD

**Issue by rkharya** [contiv/install#142]
10 node cluster having 3 UCP manager, 3 DTR and 4 worker nodes. UCP manager nodes are designated as netmaster nodes. And below v2Plugin install command was used -

[root@NFS contiv-1.0.2]# ./install/ansible/install_swarm.sh -f install/ansible/cfg.yml -u root -e ~/.ssh/id_rsa -p
Generating local certs for Contiv Proxy
Starting the installer container
Generating Ansible configuration
Using 10.65.122.61 as the master node
Verifying ansible reachability
Installing Contiv

PLAY [netplugin-node] **********************************************************
<snip>
<snip>

Failure messages for master nodes -

TASK [v2plugin : install v2plugin on master nodes] *****************************
fatal: [node2]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.0.2 ctrl_ip=10.65.122.63 control_url=10.65.122.63:9999 vxlan_port=8472 iflist=eno3 plugin_name=contiv/v2plugin:1.0.2 cluster_store=etcd://10.65.122.61:2379 plugin_role=master", "delta": "0:06:34.000383", "end": "2017-05-30 12:30:36.698503", "failed": true, "rc": 1, "start": "2017-05-30 12:24:02.698120", "stderr": "Error response from daemon: rpc error: code = 2 desc = oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/etc/openvswitch\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/plugins/81c0ce9f1c5d86cdb78bb508e4ef80e6f75bc9e6aebad00b4af526b9cc3b3d6f/rootfs\\\\\\\" at \\\\\\\"/etc/openvswitch\\\\\\\" caused \\\\\\\"stat /etc/openvswitch: no such file or directory\\\\\\\"\\\"\"", "stdout": "1.0.2: Pulling from contiv/v2plugin\n29cc2483d1ae: Verifying Checksum\n29cc2483d1ae: Download complete\nDigest: sha256:45a1684be85f94dffdc0ddcf0e41ac27820a979883e83ffe9264bf743292fd4a\nStatus: Downloaded newer image for contiv/v2plugin:1.0.2", "stdout_lines": ["1.0.2: Pulling from contiv/v2plugin", "29cc2483d1ae: Verifying Checksum", "29cc2483d1ae: Download complete", "Digest: sha256:45a1684be85f94dffdc0ddcf0e41ac27820a979883e83ffe9264bf743292fd4a", "Status: Downloaded newer image for contiv/v2plugin:1.0.2"], "warnings": []}
fatal: [node3]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.0.2 ctrl_ip=10.65.122.62 control_url=10.65.122.62:9999 vxlan_port=8472 iflist=eno3 plugin_name=contiv/v2plugin:1.0.2 cluster_store=etcd://10.65.122.61:2379 plugin_role=master", "delta": "0:06:34.087855", "end": "2017-05-30 12:30:36.765137", "failed": true, "rc": 1, "start": "2017-05-30 12:24:02.677282", "stderr": "Error response from daemon: rpc error: code = 2 desc = oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/etc/openvswitch\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/plugins/6a6359521a4a4c41e4dfefacf9d7a99f15edc3a584371085f225acd4d35be26c/rootfs\\\\\\\" at \\\\\\\"/etc/openvswitch\\\\\\\" caused \\\\\\\"stat /etc/openvswitch: no such file or directory\\\\\\\"\\\"\"", "stdout": "1.0.2: Pulling from contiv/v2plugin\n29cc2483d1ae: Verifying Checksum\n29cc2483d1ae: Download complete\nDigest: sha256:45a1684be85f94dffdc0ddcf0e41ac27820a979883e83ffe9264bf743292fd4a\nStatus: Downloaded newer image for contiv/v2plugin:1.0.2", "stdout_lines": ["1.0.2: Pulling from contiv/v2plugin", "29cc2483d1ae: Verifying Checksum", "29cc2483d1ae: Download complete", "Digest: sha256:45a1684be85f94dffdc0ddcf0e41ac27820a979883e83ffe9264bf743292fd4a", "Status: Downloaded newer image for contiv/v2plugin:1.0.2"], "warnings": []}
fatal: [node1]: FAILED! => {"changed": true, "cmd": "/usr/bin/docker plugin install --grant-all-permissions contiv/v2plugin:1.0.2 ctrl_ip=10.65.122.61 control_url=10.65.122.61:9999 vxlan_port=8472 iflist=eno3 plugin_name=contiv/v2plugin:1.0.2 cluster_store=etcd://10.65.122.61:2379 plugin_role=master", "delta": "0:06:34.614530", "end": "2017-05-30 12:30:37.305357", "failed": true, "rc": 1, "start": "2017-05-30 12:24:02.690827", "stderr": "Error response from daemon: rpc error: code = 2 desc = oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/etc/openvswitch\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/plugins/fed73514956a6ad94d241eaa30c3d8da85c0f53424e7a74091e889453d3f6c7c/rootfs\\\\\\\" at \\\\\\\"/etc/openvswitch\\\\\\\" caused \\\\\\\"stat /etc/openvswitch: no such file or directory\\\\\\\"\\\"\"", "stdout": "1.0.2: Pulling from contiv/v2plugin\n29cc2483d1ae: Verifying Checksum\n29cc2483d1ae: Download complete\nDigest: sha256:45a1684be85f94dffdc0ddcf0e41ac27820a979883e83ffe9264bf743292fd4a\nStatus: Downloaded newer image for contiv/v2plugin:1.0.2", "stdout_lines": ["1.0.2: Pulling from contiv/v2plugin", "29cc2483d1ae: Verifying Checksum", "29cc2483d1ae: Download complete", "Digest: sha256:45a1684be85f94dffdc0ddcf0e41ac27820a979883e83ffe9264bf743292fd4a", "Status: Downloaded newer image for contiv/v2plugin:1.0.2"], "warnings": []}
        to retry, use: --limit @/ansible/install_plays.retry

PLAY RECAP *********************************************************************
node1                      : ok=14   changed=10   unreachable=0    failed=1
node10                     : ok=11   changed=8    unreachable=0    failed=0
node2                      : ok=14   changed=10   unreachable=0    failed=1
node3                      : ok=14   changed=10   unreachable=0    failed=1
node4                      : ok=11   changed=8    unreachable=0    failed=0
node5                      : ok=11   changed=8    unreachable=0    failed=0
node6                      : ok=11   changed=8    unreachable=0    failed=0
node7                      : ok=11   changed=8    unreachable=0    failed=0
node8                      : ok=11   changed=8    unreachable=0    failed=0
node9                      : ok=11   changed=8    unreachable=0    failed=0

Installation failed

Full logs are attached herewith.

[contiv_install_05-30-2017.06-35-09.UTC.txt](https://github.com/contiv/install/files/1037604/contiv_install_05-30-2017.06-35-09.UTC.txt)

**Comment by gkvijay** [comment]
OVS kernel module is not present in this setup.
[root@DEE-Ctrl-3 ~]# lsmod | grep openvswitch
[root@DEE-Ctrl-3 ~]#

**Comment by rkharya** [comment]
@gkvijay - Shouldn’t we take care of this dependancy like we are doing with ETCD? Reason for this ask, with RHEL distro openvswitch kernel module comes with RHEL’s openstack repo. Customer may have to buy additional licenses from RHEL to subscribe the openstack repo. Should we include openvswitch in our installer from open source repos or we should rely on RHEL for it and expect that they will support their version of openvswitch for Conitv with subscription to openstack repos. What is our view on this? For CVD we can document either way. Thanks.

**Comment by rkharya** [comment]
Kernel module is present as part of stock RHEL OS install -
[root@DEE-Ctrl-1 ~]# modinfo openvswitch
filename:       /lib/modules/3.10.0-514.21.1.el7.x86_64/kernel/net/openvswitch/openvswitch.ko
license:        GPL
description:    Open vSwitch switching datapath
rhelversion:    7.3
srcversion:     80EF28CADBF25AC25BFDC73
depends:        nf_conntrack,nf_nat,libcrc32c,nf_nat_ipv6,nf_nat_ipv4,nf_defrag_ipv6
intree:         Y
vermagic:       3.10.0-514.21.1.el7.x86_64 SMP mod_unload modversions
signer:         Red Hat Enterprise Linux kernel signing key
sig_key:        20:3A:CB:24:2C:A4:67:7D:2A:99:8C:16:FE:B2:2D:91:DD:12:DD:89
sig_hashalgo:   sha256
[root@DEE-Ctrl-1 ~]# ls -ltr /lib/modules/3.10.0-514.21.1.el7.x86_64/kernel/net/openvswitch/openvswitch.ko
-rw-r--r--. 1 root root 172857 Apr 22 12:40 /lib/modules/3.10.0-514.21.1.el7.x86_64/kernel/net/openvswitch/openvswitch.ko

**Comment by gkvijay** [comment]
Some directories needed for OVS are missing
