### ISSUE TITLE
Reset contiv_v2plugin_install to false for non-v2 plugin install cases

### ISSUE THREAD

**Issue by neelimamukiri** [contiv/install#149]
Due to https://github.com/contiv/install/blob/master/install/ansible/install.sh#L139-L141, once you run the installer from an installation folder with V2 plugin install, you wont be able to run it with legacy swarm.
Also refactor the common auth_proxy part out from https://github.com/contiv/install/blob/master/install/ansible/install.sh#L157-L163

**Comment by gaurav-dalvi** [comment]
@neelimamukiri : can we close this one ?

**Comment by neelimamukiri** [comment]
No, this is an issue found in the merged code - its to be fixed.
