### ISSUE TITLE
v2Plugin 1.0.3 installer scripts left with 'set -x' resulting in too much verbosity 

### ISSUE THREAD

**Issue by rkharya** [contiv/install#171]
[root@NFS ansible]# cat install.sh |more
#!/bin/sh

set -xeuo pipefail <<<<<<<<<< 'x' seems to be left inadvertantly 

# This scripts runs in a container with ansible installed.
. ./install/ansible/install_defaults.sh
<snip>
<snip>

Resulting in un-pleasant verbosity -

[root@NFS contiv-1.0.3]# ./install/ansible/install_swarm.sh -f install/ansible/cfg.yml -u root -e ~/.ssh/id_rsa -p
Starting the installer container
+ . ./install/ansible/install_defaults.sh
+ pwd
+ src_conf_path=//config
+ container_conf_path=/var/contiv
+ contiv_config=/var/contiv/cfg.yml
+ tls_cert=/var/contiv/cert.pem
+ tls_key=/var/contiv/key.pem
+ def_ans_key=/var/contiv/insecure_private_key
+ host_contiv_config=//config/cfg.yml
+ host_tls_cert=//config/cert.pem
+ host_tls_key=//config/key.pem
+ host_ans_key=//config/insecure_private_key
+ contiv_network_mode=standalone
+ fwd_mode=bridge
+ aci_image=
+ export ANSIBLE_HOST_KEY_CHECKING=False
+ scheduler_provider=native-swarm
+ cluster_store=
+ install_etcd=true
+ install_scheduler=false
+ netmaster=
+ contiv_v2plugin_install=
+ getopts :n:a:im:d:v:ps: opt
+ ans_opts= --private-key /var/contiv/insecure_private_key -u root
+ getopts :n:a:im:d:v:ps: opt
+ contiv_network_mode=standalone
+ getopts :n:a:im:d:v:ps: opt
+ fwd_mode=bridge
+ getopts :n:a:im:d:v:ps: opt
+ contiv_v2plugin_install=true
+ getopts :n:a:im:d:v:ps: opt
+ echo Generating Ansible configuration
+ inventory=/.gen
+ inventory_log=/var/contiv/host_inventory.log
Generating Ansible configuration
+ mkdir -p /.gen
+ host_inventory=/.gen/contiv_hosts
+ node_info=/.gen/contiv_nodes
+ ./install/genInventoryFile.py /var/contiv/cfg.yml /.gen/contiv_hosts /.gen/contiv_nodes standalone bridge
+ [  =  ]
+ grep -A 5 netplugin-master /.gen/contiv_hosts
+ grep -m 1 ansible_ssh_host
+ awk {print $2}
+ awk -F = {print $2}

<snip>
<snip>

**Comment by gaurav-dalvi** [comment]
@dseevr 
is there any wrong with `set -xeuo pipefail` here ?

**Comment by rkharya** [comment]
-x spewing every command used in the script, on the terminal. For customer use, installation doesn't look clean and gives an impression that we are running it in de-bug mode. 
'set -euo pipefail' is ok.

**Comment by dseevr** [comment]
@gaurav-dalvi yeah, `set -x` can be removed here, though it is (as stated) sometimes useful for debugging :)

**Comment by neelimamukiri** [comment]
@rkharya, we added it to aid with debugging. It helped debug in your setup as well. We could stop showing it in the console as it is redirected to the log file anyway.

**Comment by dseevr** [comment]
I'm not sure which commit this was changed in, but none of our bash scripts are setting `-x` now.

The `1.1.0` release will therefore not have it enabled
