### ISSUE TITLE
get_latest_release.py does not work

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#179]

**Comment by gaurav-dalvi** [comment]
```
python release.py
1.0.0-beta.3
Traceback (most recent call last):
  File "release.py", line 19, in <module>
    sys.exit(1)
NameError: name 'sys' is not defined
```

**Comment by dseevr** [comment]
Is this a python 2 vs python 3 issue?

**Comment by gaurav-dalvi** [comment]
no idea. i tried to use it . It failed. so have this fix.

**Comment by dseevr** [comment]
Which version of python are you using?

**Comment by gaurav-dalvi** [comment]
I always use python 2.7.x Nobody uses python 3

**Comment by dseevr** [comment]
Ok, this is a legit issue... for some reason, we're not getting a 200 OK back from Github and we're calling `sys.exit()` without importing `sys`

Also, this doesn't work on Python 3 because we're not using `print` as a function 😄

**Comment by dseevr** [comment]
Closed in https://github.com/contiv/install/pull/180
