### ISSUE TITLE
v2 NetPlugin - Vlan range with -p option doesn't work

### ISSUE THREAD

**Issue by sisudhir** [contiv/install#182]
1. Used the command below to create a contiv network with pkt tag set to a vlan range:
netctl network create test-net -s 100.200.200.0/24 -g 100.200.200.254 -e vlan -p 2001-2005
Creating network default:test-net
>>>Network gets created.
2. 'netctl network ls' shows the network getting listed with the pkg tag 0
[root@DEE-Ctrl-C-1 ~]# netctl network ls
Tenant   Network                    Nw Type  Encap type  Packet tag  Subnet            Gateway          IPv6Subnet  IPv6Gateway  Cfgd Tag
------   -------                    -------  ----------  ----------  -------           ------           ----------  -----------  ---------
default  0xbb2wy792xxy2c5awnpcbmou  data     vxlan       0           100.100.100.0/24  100.100.100.254
default  test-net                   data     vlan        **0**           100.200.200.0/24  100.200.200.254
3. 'netctl network inspect' shows the network with pkt tag 1
[root@DEE-Ctrl-C-1 ~]# netctl network inspect test-net
{
  "Config": {
    "key": "default:test-net",
    "encap": "vlan",
    "gateway": "100.200.200.254,"
    "networkName": "test-net",
    "nwType": "data",
    "subnet": "100.200.200.0/24",
    "tenantName": "default",
    "link-sets": {},
    "links": {
      "Tenant": {
        "type": "tenant",
        "key": "default"
      }
    }
  },
  "Oper": {
    "allocatedIPAddresses": "100.200.200.254,"
    "availableIPAddresses": "100.200.200.1-100.200.200.253",
    "networkTag": "test-net.default",
    "pktTag": 1
  }
}

**vlan range was expected to be configured correctly on the contiv network**

Logs are attached herewith.

[netmaster.txt](https://github.com/contiv/install/files/1084217/netmaster.txt)
[netplugin.txt](https://github.com/contiv/install/files/1084218/netplugin.txt)

**Comment by kahou82** [comment]
@sisudhir We don't support range. Is there any documentation indicate we do?
