### ISSUE TITLE
v2plugin - vlan pkt tag -p value set to '?' still works - expected to give help option

### ISSUE THREAD

**Issue by sisudhir** [contiv/install#183]
1. While creating network with vlan pkt tag -p value set to ?, the network gets created without erroring out:
[root@DEE-Ctrl-C-1 ~]# netctl network create test-net1 -s 200.200.200.0/24 -g 200.200.200.254 -e vlan -p ?
Creating network default:test-net1
**Network got created**
2. 'netctl network inspect' shows that the vlan pkt tag is given 2 as the vlue:
[root@DEE-Ctrl-C-1 ~]# netctl network inspect test-net1
{
  "Config": {
    "key": "default:test-net1",
    "encap": "vlan",
    "gateway": "200.200.200.254,"
    "networkName": "test-net1",
    "nwType": "data",
    "subnet": "200.200.200.0/24",
    "tenantName": "default",
    "link-sets": {},
    "links": {
      "Tenant": {
        "type": "tenant",
        "key": "default"
      }
    }
  },
  "Oper": {
    "allocatedIPAddresses": "200.200.200.254,"
    "availableIPAddresses": "200.200.200.1-200.200.200.253",
    "networkTag": "test-net1.default",
    "pktTag": 2
  }
}
3. 'netctl network ls' shows pkt tag to be zero:
[root@DEE-Ctrl-C-1 ~]# netctl network ls
Tenant   Network                    Nw Type  Encap type  Packet tag  Subnet            Gateway          IPv6Subnet  IPv6Gateway  Cfgd Tag
------   -------                    -------  ----------  ----------  -------           ------           ----------  -----------  ---------
default  0xbb2wy792xxy2c5awnpcbmou  data     vxlan       0           100.100.100.0/24  100.100.100.254
default  test-net                   data     vlan        0           100.200.200.0/24  100.200.200.254
default  test-net1                  data     vlan        **0**           200.200.200.0/24  200.200.200.254

Logs are attached herewith:
[netmaster.txt](https://github.com/contiv/install/files/1084270/netmaster.txt)
[netplugin.txt](https://github.com/contiv/install/files/1084269/netplugin.txt)

**Comment by amccormi** [comment]
'netctl network ls' lists the configured state of the network, thus if the vlan pkt tag isn't specified, it will be 0, whereas 'netctl network inspect' lists the operational state, including the pkt tag value assigned. What you are seeing is expected behavior.

**Comment by kahou82** [comment]
https://github.com/contiv/netplugin/pull/1069/files
