### ISSUE TITLE
uninstall gives error

### ISSUE THREAD

**Issue by Hemakuma** [contiv/install#200]
The connection to the server localhost:8080 was refused - did you specify the right host or port?

contiv version: 1.0.3
k8s version:
[hemakuma@K8S-1 ~]$ kc version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

contiv running as binary or from container ? from container
host os ? Centos

**Comment by gaurav-dalvi** [comment]
please provide details. Its impossible to know your problem by the description you have provided.

**Comment by neelimamukiri** [comment]
Is your KUBECONFIG set correctly? Can you run regular `kubectl` commands?

**Comment by neelimamukiri** [comment]
This should be resolved with 1.1.
