### ISSUE TITLE
Contiv 1.1 - Netmaster entry not added to /etc/hosts by installer

### ISSUE THREAD

**Issue by dirkwoellhaf** [contiv/install#221]
Installer does not add "netmaster" entry in /etc/hosts, therefore "netctl" does not work on any of the hosts

Contiv 1.1
CentOS Linux release 7.3.1611 (Core)

Used installer:
install_swarm.sh -f aci_cfg.yml -e /root/.ssh/id_rsa -u root -m aci -i

**Comment by neelimamukiri** [comment]
Are you trying to access from a master node or a worker node?

**Comment by gaurav-dalvi** [comment]
also for each install,

installer adds `127.0.0.1 localhost` in /etc/hosts.

**Comment by gaurav-dalvi** [comment]
Also, uninstall script does not clear previous contiv objects.
After uninstall i still see this : 

```
netctl net ls -a
Tenant      Network  Nw Type  Encap type  Packet tag  Subnet       Gateway     IPv6Subnet  IPv6Gateway  Cfgd Tag
------      -------  -------  ----------  ----------  -------      ------      ----------  -----------  ---------
TestTenant  TestNet  data     vlan        0           10.1.1.0/24  10.1.1.254
```

**Comment by neelimamukiri** [comment]
Did you uninstall with -i & -r? @gaurav-dalvi

**Comment by gaurav-dalvi** [comment]
did with `-i`

**Comment by gaurav-dalvi** [comment]
To uninstall Contiv and Docker Legacy Swarm with ACI support:
./install/ansible/uninstall_swarm.sh -f aci_cfg.yml -e <ssh key> -u <username> -i -m aci

followed this . But there is last line : 
Note: Adding the -r flag, will cleanup any Contiv state.

**Comment by neelimamukiri** [comment]
@dirkwoellhaf , please ignore my previous question. I got a repro setup from @gaurav-dalvi and the PR is out for the fix.
