### ISSUE TITLE
legacy swarm + contiv-1.1.0-rc.1 , netmaster entry is not getting added to /etc/hosts

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#222]
When you run installer, netmaster entry is not getting added to /etc/hosts file. Because of that we are not able to talk to netmaster using netctl CLI.

Once u add entry manually everything works fine.

**Comment by neelimamukiri** [comment]
Duplicate of https://github.com/contiv/install/issues/221 .

Lets handle the discussion there.
