### ISSUE TITLE
k8s installer problem

### ISSUE THREAD

**Issue by laywin** [contiv/install#233]
hello,i followed the installer tutorial get the problem that dns container can't be created
kubectl get pods -n kube-system
![image](https://user-images.githubusercontent.com/22276474/29212212-da4ada50-7ecf-11e7-881e-9934d85170bf.png)

kubectl describe pod kube-dns-3913472980-4g8pr -n kube-system
![image](https://user-images.githubusercontent.com/22276474/29212269-2f3469d2-7ed0-11e7-80a1-83ae17bc2292.png)

search for a help,best regards!

**Comment by neelimamukiri** [comment]
kube-dns needs a default network to be started and also to be on a network that can connect to the host. You can create a default network using something like `netctl net create default-net -s 20.1.1.0/24 -g 20.1.1.1`.
If you are using vxlan mode and configured for routing `contivh1` infra network provides the host access. You can check if `contivh1` exists by running `netctl net ls`

**Comment by laywin** [comment]
thanks for your reply,i create default network but another problem come out:

![image](https://user-images.githubusercontent.com/22276474/29257150-31922ef8-80e2-11e7-974f-4dad868559b5.png)

![image](https://user-images.githubusercontent.com/22276474/29257154-46308080-80e2-11e7-9d71-0c713aab497f.png)

**Comment by neelimamukiri** [comment]
Does `kubectl get pods -n kube-system` show all pods running? Can you get the logs for /var/contiv/log/netplugin.log?

**Comment by laywin** [comment]
hello,i get the logs,my kubernetes version is 1.6.1,contiv is 1.1.1.

kubectl get pods -n kube-system
![image](https://user-images.githubusercontent.com/22276474/29298963-1b030be6-819e-11e7-9d6f-48fa86671d73.png)

/var/contiv/log/netplugin.log
![image](https://user-images.githubusercontent.com/22276474/29299081-cd92d46c-819e-11e7-9d91-9b817948ed9f.png)


kubectl logs contiv-netplugin-c7277 -n kube-system

![image](https://user-images.githubusercontent.com/22276474/29298907-b82bf6cc-819d-11e7-9b78-7f9c662f595b.png)

/var/contiv/log/netmaster.log
![image](https://user-images.githubusercontent.com/22276474/29298935-e43e49b8-819d-11e7-87d1-d129e3ba5eba.png)

**Comment by laywin** [comment]
i change the k8s version to 1.6.5, everything is ok...

**Comment by neelimamukiri** [comment]
Kubeadm 1.6.0 & 1.6.1 won't work with Contiv installed as pods due to https://github.com/kubernetes/kubernetes/issues/44041. https://github.com/contiv/install also lists 1.6.2+ as a requirement.
