### ISSUE TITLE
Contiv 1.1.1 UI doesn't list out Group Tag used while creating groups

### ISSUE THREAD

**Issue by rkharya** [contiv/install#241]
'netctl` cli does show this as a value to `CfgdTag`, where as we do not see this value through UI. This is important to know the tag value, in-order to create Docker Network for a group attached to specific contiv back-end network. 

There is mismatch in information display between UI and CLI.
![screen shot 2017-08-24 at 12 49 58 pm](https://user-images.githubusercontent.com/12057795/29654521-3120b9b2-88cb-11e7-8b30-31d088a50a8a.png)
![screen shot 2017-08-24 at 12 50 11 pm](https://user-images.githubusercontent.com/12057795/29654520-3120acf6-88cb-11e7-8454-39b0cfd678a4.png)

**Comment by kahou82** [comment]
This is an UI bug. The fix is in https://github.com/contiv/contiv-ui/pull/300.

**Comment by dseevr** [comment]
This fix was included in 1.1.5.  Please reopen if you encounter any issues
