### ISSUE TITLE
contiv 1.1.6 installtion fails: as the path to netplugin-1.1.6.tar.bz2 is not available

### ISSUE THREAD

**Issue by sisudhir** [contiv/install#287]
**Description**: Installation of Contiv 1.1.6 full version failed with an error "*Unable to find '/var/contiv_cache/netplugin-1.1.6.tar.bz2' in expected paths*".

**Steps followed**:
1. On the master node of the docker swarm cluster, downloaded the full version installer bundle using:
_curl -L -O https://github.com/contiv/install/releases/download/$VERSION/contiv-full-$VERSION.tgz_
2. Untared the file and Modified the env.json with the proxy settings to suit our environment:
`{
  "docker_version": "1.12.6",
  "aci_gw_image": "contiv/aci-gw:08-04-2017.2.2_2j",
  "contiv_network_version": "1.1.6",
 "env":{ "http_proxy":"http://64.102.255.40:8080", "HTTP_PROXY":"http://64.102.255.40:8080", "https_proxy":"http://64.102.255.40:8080", "no_proxy":"127.0.0.1,localhost,netmaster,10.65.121.121,10.65.121.122,10.65.121.123,10.65.121.124,DEE-Ctrl-C-1,DEE-Ctrl-C-2,DEE-Ctrl-C-3,DEE-Wrk-C-1"},
  "etcd_peers_group": "netplugin-master",
  "service_vip": "__NETMASTER_IP__",
  "validate_certs": false,
  "cluster_store": "__CLUSTER_STORE__",
  "auth_proxy_image": "contiv/auth_proxy:1.1.6",
  "docker_reset_container_state": __DOCKER_RESET_CONTAINER_STATE__,
  "docker_reset_image_state": __DOCKER_RESET_IMAGE_STATE__,
  "etcd_cleanup_state": __ETCD_CLEANUP_STATE__,
  "auth_proxy_local_install": true,
  "contiv_network_local_install": true,
  "vxlan_port": __VXLAN_PORT__,
  "netctl_url": "http://__NETMASTER_IP__:9999",
  "contiv_v2plugin_install": __CONTIV_V2PLUGIN_INSTALL__,
  "contiv_v2plugin_image": "contiv/v2plugin:1.1.6"
}`
3. Ran the ansible playbook. The installation failed at:
_TASK [contiv_network : copy contiv binaries] ***********************************
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/var/contiv_cache/netplugin-1.1.6.tar.bz2' in expected paths."}
fatal: [node2]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/var/contiv_cache/netplugin-1.1.6.tar.bz2' in expected paths."}
fatal: [node3]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/var/contiv_cache/netplugin-1.1.6.tar.bz2' in expected paths."}
	to retry, use: --limit @/ansible/install_plays.retry_

**Please find the logs attached:**
[contiv_install_11-04-2017.07-37-07.UTC.log](https://github.com/contiv/install/files/1445208/contiv_install_11-04-2017.07-37-07.UTC.log)
[host_inventory.log](https://github.com/contiv/install/files/1445209/host_inventory.log)

**Comment by chrisplo** [comment]
@sisudhir Please try again with updated release full installer

**Comment by kahou82** [comment]
This is verified by @sisudhir
