### ISSUE TITLE
When I installed the script in a Kubernetes environment, I got the following error:DaemonSet.extensions "contiv-netplugin" is invalid

### ISSUE THREAD

**Issue by llunplay** [contiv/install#320]
Hi all
     When I installed the script in a Kubernetes environment, I got the following error:

[root@service-6-140 contiv-1.1.6]# ./install/k8s/install.sh -n 10.11.6.140
Installing Contiv for Kubernetes
secret "aci.key" created
Generating local certs for Contiv Proxy
Created ./local_certs/local.key and ./local_certs/cert.pem
Setting installation parameters
Applying contiv installation
To customize the installation press Ctrl+C and edit ./.contiv.yaml.
configmap "contiv-config" created
replicaset "contiv-api-proxy" created
daemonset "contiv-etcd" created
Error from server (Invalid): error when creating "./.contiv.yaml": DaemonSet.extensions "contiv-netplugin" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policy
Error from server (Invalid): error when creating "./.contiv.yaml": ReplicaSet.extensions "contiv-netmaster" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by policy

**Comment by tiewei** [comment]
@llunplay thanks for raising the issue, could you provide the content of `./.config.yaml`, k8s version and k8s configurations ( you can get it by provide `ps -ef|grep kube` ) so that we can try reproducing it ?

**Comment by llunplay** [comment]
@tiewei thank you for your help, this is the k8s version and k8s configurations "
[root@service-6-140 ~]# ps -ef|grep kube
root       6161      1  0 Oct27 ?        00:02:10 /usr/bin/flanneld -etcd-endpoints=http://10.11.6.140:2379,http://10.11.6.148:2379,http://10.11.6.149:2379 -etcd-prefix=/kube-centos/network
kube       6844      1  1 Dec15 ?        00:51:35 /usr/bin/kube-controller-manager --logtostderr=true --v=0 --master=http://10.11.6.140:8080
kube       6845      1  0 Dec15 ?        00:05:08 /usr/bin/kube-scheduler --logtostderr=true --v=0 --master=http://10.11.6.140:8080
kube       6998      1  0 Dec15 ?        00:31:07 /usr/bin/kube-apiserver --logtostderr=true --v=0 --etcd-servers=http://10.11.6.140:2379,http://10.11.6.148:2379,http://10.11.6.149:2379 --insecure-bind-address=0.0.0.0 --allow-privileged=false --service-cluster-ip-range=10.254.0.0/16
root      23668  23568  0 10:03 pts/0    00:00:00 grep --color=auto kube"

and then I didn't find  ./.config.yaml in "contiv-1.1.6",like this 👍 
[root@service-6-140 contiv-1.1.6]# find . -name config.yaml
[root@service-6-140 contiv-1.1.6]# 


I just contacted k8s, thanks again for your support！

**Comment by dseevr** [comment]
The file is `.config.yaml`:

```
find . -type f -name .config.yaml
```

**Comment by llunplay** [comment]
I still can not find that file,this is the log ,thanks for your help!!
[root@service-6-140 contiv-1.1.7]# find . -type f -name .config.yaml
[root@service-6-140 contiv-1.1.7]# ls
aci.key  ansible  contiv_cache  install  local_certs  README.md
[root@service-6-140 contiv-1.1.7]# find . -type f -name .config.yaml
[root@service-6-140 contiv-1.1.7]#

**Comment by llunplay** [comment]
Thanks for your help, the problem has been solved.With the help of a buddy, we can be sure that this is a policy issue.And Here is the solution.


vim /etc/kubernetes/config 
###

KUBE_ALLOW_PRIV="--allow-privileged=true"
