### ISSUE TITLE
What is the difference between the two `nw type` -- `infra` and `data`?

### ISSUE THREAD

**Issue by KeithTt** [contiv/install#322]
Is there a doc about this...?

```
# netctl network ls
Tenant   Network      Nw Type  Encap type  Packet tag  Subnet        Gateway    IPv6Subnet  IPv6Gateway  Cfgd Tag
------   -------      -------  ----------  ----------  -------       ------     ----------  -----------  ---------
default  contivh1     infra    vxlan       0           132.1.1.0/24  132.1.1.1
default  default-net  data     vxlan       6           30.0.0.0/10   30.0.0.1                            6
```

**Comment by vhosakot** [comment]
@KeithTt http://contiv.github.io/documents/tutorials/networking-kubernetes-16.html has documentation about the continue default network:

```
[vagrant@kubeadm-master ~]$ netctl net ls -a
Tenant   Network      Nw Type  Encap type  Packet tag  Subnet        Gateway    IPv6Subnet  IPv6Gateway  Cfgd Tag
------   -------      -------  ----------  ----------  -------       ------     ----------  -----------  ---------
default  contivh1     infra    vxlan       0           132.1.1.0/24  132.1.1.1
default  default-net  data     vxlan       0           20.1.1.0/24   20.1.1.1
```

**Comment by KeithTt** [comment]
@vhosakot I know how to create it. I want to find out the difference between the two `Nw type`...

**Comment by vhosakot** [comment]
@KeithTt The "Networks in Contiv" section in http://contiv.github.io/documents/networking/concepts.html has the difference between contiv infra network and application (data) network:

> Networks in Contiv
>
> Contiv allows you to define two types of networks:
>
> application network - Network used by container workloads
> infrastructure network - Create a virtual network in the host namespace. For example, infrastructure networks are used by the virtual layer of host-resident infrastructure services such as monitoring.

**Comment by KeithTt** [comment]
@vhosakot Got it, thanks a lot!
