### ISSUE TITLE
Get https://10.96.0.1:443/api/v1/secrets: read tcp 30.0.0.5:50738->10.96.0.1:443: read: connection reset by peer

### ISSUE THREAD

**Issue by KeithTt** [contiv/install#323]
I met this issue when access dashboard, it seems something about certs or secrets?

30.0.0.0/10 is my podSubnet, and 30.0.0.5 is the pod IP.

![image](https://user-images.githubusercontent.com/15189954/34170688-cd0a95ac-e526-11e7-8094-a9678aea74b1.png)

Everything works when use calico, so i think the issue is something about contiv, pls help...

**Comment by dseevr** [comment]
@neelimamukiri is this the same error you were seeing?

**Comment by KeithTt** [comment]
@dseevr There are 3 netmasters in my environment.

I have rebuild the cluster one more time step by step to locate the problem, it appears when there are multi-netmasters, and everything is ok when there is only one netmaster.

I installed contiv like this:

1、replace the CA path
```
# vim install/k8s/k8s1.6/contiv.yaml
```

2、change the kind of netmaster to DaemonSet

3、copy the certs to all the 3 masters in `/var/contiv/`

4、deploy
```
# ./install/k8s/install.sh -n 192.168.6.16 -w routing -s etcd://192.168.6.17:6666
```

Have I missed anything to deploy 3 netmasters for HA?

**Comment by KeithTt** [comment]
Finally I found the problem, there is one cert signed wrong......I spend so much time looking for it, sad.

@dseevr Thanks.
