### ISSUE TITLE
Installer needs  to exit with a non-zero status if it fails

### ISSUE THREAD

**Issue by dojacobs** [contiv/install#34]
There's a problem with the repo that is preventing Installer from getting a certain RPM.

The installer prints "Install Failed" but since this command succeeds, the script exits with status = 0, which means the entire script succeeded.

Unfortunately this means for automation and other integration systems, Installer will always "succeed" - even when it failed.

Exiting with status code=1 is sufficient in the case of a failure.

**Comment by dojacobs** [comment]
I can't mark this as [BUG].

**Comment by gaurav-dalvi** [comment]
PR : https://github.com/contiv/install/pull/36

**Comment by neelimamukiri** [comment]
Is there anything else to be done here?
