### ISSUE TITLE
How can i use contiv in k8s' deployment?

### ISSUE THREAD

**Issue by liucimin** [contiv/install#341]
In the page of the contiv http://contiv.github.io/documents/tutorials/networking-kubernetes-16.html
I just get the use in pods.
But most time,we want to use the net in Deployment or RC,
So from where can i get the guide to use this in Deployment ?

**Comment by yaliee** [comment]
I guess you can refer contiv/vpp

**Comment by darkounet** [comment]
I'm interested too with this, how can we put an IP in a specific vlan for a service ?
