### ISSUE TITLE
Do I miss some steps? Contiv 1.2.0 with K8S 1.9.2(Never succeeded! Need help)

### ISSUE THREAD

**Issue by ghost** [contiv/install#343]
Hi Master:

Do I miss some steps?
Do I need to change cni version from 0.1.0 to 0.6.0?
Thanks

k8s-master:~$ kubectl get pods(Result)
-----------------
NAME                       READY     STATUS                   RESTARTS   AGE
hello-docker-web   0/1           ContainerCreating   0                  49m

k8s-master:~$ kubectl describe pods hello-docker-web(Result)
-----------------
Events:
  Type     Reason                  Age               From                  Message
  Normal   Scheduled               30s               default-scheduler     Successfully assigned hello-docker-web to k8s-worker1
  Normal   SuccessfulMountVolume   30s               kubelet, k8s-worker1  MountVolume.SetUp succeeded for volume "default-token-t7wrr"
  Warning  FailedCreatePodSandBox  8s (x2 over 21s)  kubelet, k8s-worker1  Failed create pod sandbox.
  Normal   SandboxChanged          8s (x2 over 21s)  kubelet, k8s-worker1  Pod sandbox changed, it will be killed and re-created.

Operation Systems
-----------------
k8s-master  192.168.1.10(Ubuntu 16.04)
K8s-worker1 192.168.1.11(Ubuntu 16.04)

Kubernetes
-----------------
Kubernetes 1.9.2
sudo kubeadm init --apiserver-advertise-address=192.168.1.10 --service-cidr=10.1.1.0/24
The kube-dns remove manually

Contiv
-----------------
curl -L -O https://github.com/contiv/install/releases/download/1.2.0/contiv-1.2.0.tgz
sudo ./install/k8s/install.sh -n 192.168.1.10 -g 10.1.2.254 -i 10.1.2.0/24

k8s-master:~$ netctl network ls
Tenant   Network    Nw Type  Encap type  Packet tag  Subnet       Gateway     IPv6Subnet  IPv6Gateway  Cfgd Tag
default  contivh1       infra    vxlan       0           10.1.2.0/24  10.1.2.254                          
default  contivnet3  data     vxlan       3           10.1.3.0/24  10.1.3.254  

hello-docker-web.yaml
------------------------------------------------------------------
#pod
kind: Pod
apiVersion: v1
metadata:
   name: hello-docker-web
   labels:
     app: hello-docker-web
     io.contiv.tenant: default
     io.contiv.network: contivnet3
     io.contiv.net-group: contivnet3-group
spec:
   containers:
   \- name: hello-docker-web
     image: xxx/hello-docker-web:v1.0.0
     command:
       \- sleep
       \- "7200"
     ports:
     \- containerPort: 80
#service
kind: Service
apiVersion: v1
metadata:
 labels:
   app: hello-docker-web
 name: hello-docker-web
spec:
 type: NodePort
 ports:
       \- port: 80
     targetPort: 80
     nodePort: 30080
 selector:
   app: hello-docker-web

**Comment by piaohai** [comment]
how to fix it,tks?
