### ISSUE TITLE
Installer for Docker-Swarm needs to exit with status code != 0 on all failures

### ISSUE THREAD

**Issue by dojacobs** [contiv/install#50]
The installer doesn't always exit with a non-zero status code on a failure.

Shell scripts succeed (0) or fail (non-zero) based on the last command issued.  If that command is an echo, it succeeds and the script exits with 0.

The problem with this is Jenkins uses the exit codes of commands and scripts to determine if the step succeeded or not.  So printing an error statement and exiting with 0 means "Success."

The last error Installer encountered was that the Netmaster didn't come up after 10 tries, so it printed an error messaged and exited...with 0.

**Comment by dojacobs** [comment]
Edited title to point out this is for the docker-swarm installer.

**Comment by neelimamukiri** [comment]
Should be fixed with the latest code base.
