### ISSUE TITLE
Contiv k8s install.sh needs to exit with non-zero if failure

### ISSUE THREAD

**Issue by dojacobs** [contiv/install#51]
Jenkins tried running the K8s install.sh but did it in the wrong directory and didn't do it as root.

This caused many errors, but the script still thought it succeeded, and printed out how to get to the Contiv UI.

If an error is encountered (not root, missing file, etc.) print an error message and exit with status = 1.

**Comment by dseevr** [comment]
@dojacobs https://github.com/contiv/install/pull/52 has been merged... you can pull on master to get the latest code.  If you're still hitting this issue, let me know
