### ISSUE TITLE
k8s/install.sh fwd-mode routing doesn't work

### ISSUE THREAD

**Issue by tiswanso** [contiv/install#59]
k8s/install.sh attempts to use netctl from location where it was prior to move to /usr/bin.  So, the fwd-mode doesn't get set to routing.

https://github.com/contiv/install/blob/master/install/k8s/install.sh#L247

This issue is in master as well as 1.0.0-beta.3

**Comment by neelimamukiri** [comment]
Fixed with https://github.com/contiv/install/commit/d207b6609f88d4b4bed02e2e7de98f909dde4c1b
