### ISSUE TITLE
add aci-gw load option if there is already docker image tarball

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#6]
As aci-gw container image can take longer time depending upon your network connection. so please make the flag that if docker image tar file is there just load from there instead of doing docker pull.

**Comment by gaurav-dalvi** [comment]
@neelimamukiri : Please assign it yourself I dont have permission to add Assignees on this repo.

**Comment by neelimamukiri** [comment]
Corresponding ansible PR is https://github.com/contiv/ansible/pull/322
