### ISSUE TITLE
Container 101 tutorial not working anymore

### ISSUE THREAD

**Issue by JoePython1** [contiv/install#60]
http://contiv.github.io/documents/tutorials/container-101.html

[vagrant@tutorial-node1 ~]$ etcdctl cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

[vagrant@tutorial-node1 ~]$ netctl version
ERRO[0030] Get http://netmaster:9999/version: dial tcp 192.168.2.10:9999: i/o timeout 
[vagrant@tutorial-node1 ~]$ logout
Connection to 127.0.0.1 closed.

**Comment by rhim** [comment]
dup of contiv/contiv.github.io#51
