### ISSUE TITLE
What is the default user name and password when contiv is first set up?

### ISSUE THREAD

**Issue by alpha-li** [contiv/install#63]

**Comment by dseevr** [comment]
Username: admin

Password: admin

**Comment by alpha-li** [comment]
I had a try ,after inputing that info ,nothing happeded.  It seems that admin/admin is correct, but I can not login still. What shall I do?

**Comment by neelimamukiri** [comment]
Do you see any specific error? Did you use the swarm/kubernetes installer?

**Comment by dseevr** [comment]
Possibly related to https://github.com/contiv/contiv-ui/issues/282 ?

Could you put your details (OS, browser, versions, etc.) there?

**Comment by alpha-li** [comment]
> @neelimamukiri I can't see any specific error.I use the swarm installer.

**Comment by alpha-li** [comment]
@dseevr 
OS： MacOS  10.12.3
Browser： Chrome 56.0
Contiv：1.0.0-full-beta.3
VM Manager: Virtualbox 5.0.26

**Comment by dseevr** [comment]
@alpha-li thanks for the info.  It seems you are encountering the exact same issue as https://github.com/contiv/contiv-ui/issues/282.  This bug is not related to the installer so I will close this thread and you can subscribe to that one for updates.  Thanks again and I am very sorry for the inconvenience!  😞

**Comment by dseevr** [comment]
Actually, @alpha-li would you be willing to try one thing for me?

Could you go inside the VM (`vagrant ssh ...`) and `sudo yum install ntp`, make sure the clock syncs, and then try again?

**Comment by neelimamukiri** [comment]
@alpha-li, were you able to try @dseevr's suggestion?

**Comment by neelimamukiri** [comment]
Should be resolved with https://github.com/contiv/contiv-ui/commit/c0f6ec82b3879e661b2b0e585de3553ae2f7d1f8. Please reopen if issue exists after beta 5.

**Comment by alpha-li** [comment]
@neelimamukiri Thank u very much! I will try it later.
