### ISSUE TITLE
Ansible Options hardcoded in install_swam.sh and uninstall_swarm.sh causes issues in non-Vagrant environments

### ISSUE THREAD

**Issue by sjeuk** [contiv/install#64]
The install_swarm.sh and the uninstall_swarm.sh have the Ansible options hardcoded to a vagrant like environment. 

# Ansible options. By default, this specifies a private key to be used and the vagrant user
ans_opts=""
ans_user="vagrant"
ans_key=$src_conf_path/insecure_private_key
install_scheduler=""

Should either be made accessible through the CLI as parameters or mentioned in document to modify these values according to setup environment. 

If not modified, and a non-Vagrant environment is used this causes problems with login to other nodes.

**Comment by neelimamukiri** [comment]
These are the defaults.
The scripts take ansible user with the -u parameter, ssh key with the -e parameter and any additional ansible options with the -a parameter.
