### ISSUE TITLE
have runtime parameter to specify aci-gw version

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#7]
Current installer does not take aci-gw container customer image information as a command line. Can we please make that parameter as run time so that I can  pass in to script ?

aci-gw-image="contiv/aci-gw:<some version>"

**Comment by gaurav-dalvi** [comment]
@neelimamukiri : Please assign it yourself.

**Comment by neelimamukiri** [comment]
For reference, we decided on having the versions and images hard coded at build time, to allow for the support matrix to match the test matrix. The env file mechanism allows overriding any of the options, but it is not simple, so restricted to cases where there is a one off requirement. We want to make this a command line option for aci-gw container as the aci-gw image has to match the APIC version and not a contiv build.

**Comment by gaurav-dalvi** [comment]
previous net_demo_installer script was very flexible on this. contiv/aci-gw container is integral part of contiv (in fact one of the most important)  So installer should be flexible to take any image of aci-gw container.
