### ISSUE TITLE
etcd not installed when the script is run without -i

### ISSUE THREAD

**Issue by camrossi** [contiv/install#72]
Hi,

If docker is already installed but etcd is not the script logic has a bug and won't install etcd.

You first do this:
if [ "$cluster_store" == "" ];then
  cluster_store="etcd://$service_vip:2379"
fi
and then you check 

if [ "$cluster_store" = "" ];
INSTALL ETCD

This will clearly never work

**Comment by neelimamukiri** [comment]
Should be resolved with 694673b32ef6498546abd80faa6dc57e45a57de1.
https://github.com/contiv/install/commit/694673b32ef6498546abd80faa6dc57e45a57de1#diff-9c3581b3544b2a45a38ca4fa19b7dbc6R143

It will be available in the next release or you can build a release with make build.
