### ISSUE TITLE
Permission denied (publickey) error when connecting through SSH on AWS after Contiv installation

### ISSUE THREAD

**Issue by overip** [contiv/install#78]
There is an issue that may most likely be caused by Contiv.
Immediately after installing Contiv on an AWS instance the home of the user change ownership. The new owner of the home directory becomes "staff".
So if you have an instance with Ubuntu OS, the owner of /home/ubuntu is replaced by "staff", causing the instance to be no more accessible with SSH. The workaround is to create a new instance, stop old and new instance, detaching the volume from old instance, attaching the volume to new instance then starting the new instance and then change the ownership of the home folder. Then you can stop the new instance, detach the volume from old instance, attach it to the old instance, and finally the old instance is accessible again via SSH.

**Comment by neelimamukiri** [comment]
So running tar as root was causing this issue.
tar oxf contiv-1.0.0-beta.4.tgz works fine.
tar xf contiv-1.0.0-beta.4.tgz changes the owner of home to the user who created the tar bundle.
I will update the documentation accordingly. Amazing find @overip, thanks for helping repro/root cause it.
