### ISSUE TITLE
Update k8s installer to support liveness checks

### ISSUE THREAD

**Issue by neelimamukiri** [contiv/install#82]
Installer changes corresponding to https://github.com/contiv/netplugin/pull/807

**Comment by jojimt** [comment]
The following changes are required: 1) Set contiv fwd-mode to "routing" 2) Create an "infra" network with name contivh1 and a default gateway specified. E.g. netctl net create -n infra -s 132.1.1.0/24 -g 132.1.1.1 contivh1
