### ISSUE TITLE
while doing make demo-swarm getting this error

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/install#84]
git clone latest install code
cd install
export BUILD_VERSION=1.0.0-beta.4
make demo-swarm

```
==> contiv-node4: Complete!
BUILD_VERSION= make install-test-swarm
~/Desktop/INSTALL/install/cluster ~/Desktop/INSTALL/install
~/Desktop/INSTALL/install
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make[1]: *** [install-test-swarm] Error 1
make: *** [demo-swarm] Error 2
```

**Comment by neelimamukiri** [comment]
https://github.com/contiv/install/issues/85 causes the "BUILD_VERSION= " in
BUILD_VERSION= make install-test-swarm above. So both issues are the same.

**Comment by gaurav-dalvi** [comment]
#85 expects certain python modules.  This one is regarding the error which we are getting in the end of `make demo-swarm` how come both issues are same ?
